### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by maciekkossuda** [tpay-com/tpay-magento2-basic#85]
Hello,

in the latest `2.3.0` version we get an error during compilation (`setup:di:compile`)
```
Preference declared for "Tpay\OpenApi\Utilities\CertificateProvider" as "Tpay\OpenApi\Utilities\CacheCertificateProvider", 
but the latter has not been included in dependency injection compilation.
```

**Comment by KamilBalwierz** [comment]
Hi,

I am unable to reproduce this issue on my test environment:
```
$ composer show tpay*
tpay-com/module-hyva-checkout 1.1.0 Hyvä Checkout compatibility for Magento2 Tpay payment module
tpay-com/tpay-openapi-php     2.0.0 Tpay OpenAPI library
tpay-com/tpay-php             2.4.7 Tpay.com library
tpaycom/magento2basic         2.3.0 Tpay payments module
```
Mentioned classes are provided by OpenAPI SDK 2.0 - this is new version requirement for Magento module version 2.3.0 and should be enforced by composer. Please make sure You have proper OpenAPI SDK version installed.

**Comment by maciekkossuda** [comment]
@KamilBalwierz It doesn't work with Magento 2.4.8, with 2.4.7-p5 works fine.

**Comment by KamilBalwierz** [comment]
Candidate for final solution can be found here https://github.com/tpay-com/tpay-magento2-basic/pull/86

**Comment by KamilBalwierz** [comment]
Solution published as version 2.3.1 https://github.com/tpay-com/tpay-magento2-basic/releases/tag/2.3.1
